baseURL = "https://blog.loicmdivad.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Lo√Øc M. Divad"
theme = "cayman-hugo-theme"
summarylength = 50
# Google analytics
# googleAnalytics = "UA-123456789-1"

# Disqus comments
# disqusShortname = "yourdiscussshortname"

# Syntax highlighting
pygmentsCodefences = true
pygmentsStyle = "manni"

[taxonomies]
  tag = "tags"

[author]
  name = "Lo√Øc DIVAD"

[permalinks]
  posts = "/:section/:year/:month/:title/"
  talks = "/:section/:title/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true

[params]
  extra_css = ["css/fontawesome.css"]
  #dateform = "Jan 2, 2006"
  #dateformshort = "2006-01-02"
  #dateformNumTime = "2006-01-02 15:04 MST"

  project_name = "Lo√Øc M. DIVAD"
  project_tagline = "Event Streams and Monads in the Clouds üë®üèæ‚Äçüíªüçπ"
  mainSections = "posts"

  justifyContent = true
  header_img = "banner.jpg"

  # Breakpoints
  large_breakpoint = "64em"
  medium_breakpoint = "42em"

  # Header colors
  header_heading_color = "#eaeaea"
  header_background_color = "#733c3c"
  header_background_color_secondary = "#f2a444"

  # Text colors
  section_headings_color = "#733c3c"
  body_text_color = "#606c71"
  body_link_color = "#d8753a"
  blockquote_text_color = "#819198"

  # Code colors
  code_background_color = "#f3f6fa"
  code_text_color = "#be533b"

  # Border colors
  border_color = "#dce6f0"
  table_border_color = "#c4c5c4"
  hr_border_color = "#eff0f1"

  footer = "All rights reserved [Lo√Øc DIVAD](https://blog.loicmdivad.io) ¬© 2020 ‚Ä¢ Made with [Hugo](https://gohugo.io/)."
  footer_img_credits = "Themed by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme). Header Photo by [Daniel Gregoire](https://unsplash.com/@yeeeeeeha?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText) on [Unsplash](https://unsplash.com/s/photos/daniel-gregoire?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText)."

[params.socials]
  linkedin = "https://www.linkedin.com/in/lo%C3%AFc-divad-3a5a9893/"
  twitter = "https://twitter.com/LoicMDivad"
  github = "https://github.com/DivLoic"

[menu]
  [[menu.nav]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.nav]]
    name = "Talks"
    url = "/talks/"
    weight = 2

  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 4

[imaging]
# See https://github.com/disintegration/imaging
# CatmullRom is a sharp bicubic filter which should fit the docs site well with its many screenshots.
# Note that you can also set this per image processing.
  resampleFilter = "CatmullRom"

# Default JPEG quality setting. Default is 75.
  quality = 75

  anchor = "smart"